module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Tests', [
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Ann',
        number: 1,
        distance: 1000,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'John',
        number: 2,
        distance: 900,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Elizabeth',
        number: 2,
        distance: 800,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Ramsy',
        number: 3,
        distance: 700,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Gvidon',
        number: 4,
        distance: 600,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Alexa',
        number: 5,
        distance: 500,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Anzo',
        number: 6,
        distance: 400,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Ruby',
        number: 7,
        distance: 300,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Amster',
        number: 8,
        distance: 200,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Sergo',
        number: 9,
        distance: 100,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Ameli',
        number: 12,
        distance: 1100,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'George',
        number: 29,
        distance: 100,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Sam',
        number: 25,
        distance: 2100,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Sergio',
        number: 12,
        distance: 1300,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Fiona',
        number: 25,
        distance: 1220,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Malkoln',
        number: 23,
        distance: 100,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Leo',
        number: 16,
        distance: 1050,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Alexa',
        number: 9,
        distance: 560,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Sergo',
        number: 9,
        distance: 100,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Liza',
        number: 15,
        distance: 1500,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Raudy',
        number: 21,
        distance: 1310,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Tom',
        number: 18,
        distance: 2400,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Kimberly',
        number: 31,
        distance: 100,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Emma',
        number: 29,
        distance: 3200,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Ilon',
        number: 24,
        distance: 500,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Yi',
        number: 27,
        distance: 2200,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Piter',
        number: 6,
        distance: 1570,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Sergo',
        number: 21,
        distance: 2990,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        date: new Date(new Date() - Math.random() * (1e+12)),
        name: 'Barry',
        number: 30,
        distance: 2480,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ], {});
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Tests', null, {});
  },
};
